FROM mcr.microsoft.com/dotnet/aspnet:8.0-preview as base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-preview as build
WORKDIR /src
COPY ["GrpcGreeter.csproj" , "GrpcGreeter/"]
RUN dotnet restore "GrpcGreeter/GrpcGreeter.csproj"
COPY ./ ./GrpcGreeter
WORKDIR "/src/GrpcGreeter"
RUN dotnet build "GrpcGreeter.csproj" -c Release -o /app/build

FROM build as publish
RUN dotnet publish "GrpcGreeter.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "GrpcGreeter.dll" ]
